// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Post struct {
	ID       int       `json:"id"`
	Created  time.Time `json:"created"`
	ThreadID int       `json:"thread_id"`
}

type Thread struct {
	ID    int     `json:"id"`
	Posts []*Post `json:"posts"`
}

func (Thread) IsEntity() {}
