package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"

	"github.com/amit-ksh/supergraph-top-n-challenge/services/posts/graph/model"
)

// FindThreadByID is the resolver for the findThreadByID field.
func (r *entityResolver) FindThreadByID(ctx context.Context, id int) (*model.Thread, error) {
	var posts []*model.Post

	return &model.Thread{
		ID:    id,
		Posts: posts,
	}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
