// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Thread struct {
	ID      int       `json:"id"`
	Created time.Time `json:"created"`
}

func (Thread) IsEntity() {}
